"""added Foreign Keys

Revision ID: dc4d2cd51451
Revises: a6e397bffa0c
Create Date: 2023-06-05 12:21:16.693804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4d2cd51451'
down_revision = 'a6e397bffa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_prices_product_id_products'), 'products', ['product_id'], ['unique_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_vendor_id_vendors'), type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prices_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
